### ISSUE TITLE
ERD 작성

### ISSUE THREAD

**Issue by suhani93** [2021-study/point-shop#16]
## ERD 작성
>  요구사항 명세를 기반으로 ERD 작성

## 진행 사항
- [ v ] 회원
- [ v ] 상품
- [ v ] 주문
- [ v ] 포인트

ERD : https://www.erdcloud.com/d/cnW6oRmkHdKR9HTbE

**Comment by humanitas03** [comment]
#### 프로젝트 물리 DB ERD 입니다(ver 0.0.1)

* 이슈는 Closed 하고  Major한 ERD 변경사항이 있을 때 다시 Open을 하는게 어떤가 싶네요.

![physical-model-v 0 0 1](https://user-images.githubusercontent.com/16380977/140636131-72a09544-19a4-4896-837d-4d6173594548.png)
