### ISSUE TITLE
유저 로그인 로직 구현

### ISSUE THREAD

**Issue by suhani93** [2021-study/point-shop#29]
## 설명
> 일반 유저의 로그인 로직 구현
> SNS 유저의 로그인 로직 구현

## 진행 사항
- [ ] 일반 유저의 로그인 구현
- [ ] SNS 유저의 로그인 로직 구현

**Comment by qkrwldn222** [comment]
일반 유저랑,SNS 유저 공통으로 가고 CustomUserDetailsService에서 loadUserByUsername 로그인, AuthenticationProvider에서 sns_provider_type값으로 일반유저 sns유저 구분하면 되지 않을까요? (구별 해야되는 이유가 있을까여?)

UserDetails 은 권한이 일단 없어서 TB_USER_INFO 값만 가져오면 큰 문제는 없을거 같습니당(?)

**Comment by suhani93** [comment]
@qkrwldn222  일반 유저랑 SNS 유저가 서로 다른 로직으로 인증이 구현되어야 하기 때문에 (ex ) 일반 유저는 로그인 시 ID, PW 가 필요, SNS 로그인은 해당 사이트에 요청해서 받아온 값이 필요) 한쪽에서 다 처리하는 것보다 각각의 특성에 맞게 처리하는게 좋을 거라고 생각이 됩니다.

**Comment by humanitas03** [comment]
이미 수한님이 한번 언급주셨는데.. TMI 생략하고 결론만 이야기하자면..
**단일 책임 원칙(SRP)** 관점입니다..

**Comment by qkrwldn222** [comment]
@suhani93 궁금한게 초기 SNS로 로그인시에 저희 DB User 테이블에 저장되나요?

**Comment by suhani93** [comment]
@qkrwldn222 구현하기 나름입니다.

**Comment by humanitas03** [comment]
@qkrwldn222 
회원 테이블 설계방향 논의할 때 Table 분리 안하고 하나로 관리하는 걸로 결론을 지었던 걸로 알고있습니다.

**Comment by enjay27** [comment]
OAuth2UserService 구현 해보는 중인데요

![endpoint설정](https://user-images.githubusercontent.com/23338687/140527520-9df8e8dd-b431-4f92-8369-50aa2a63349e.png)

userInfoEndPoint() 에서 CustomOAuthUserService 설정을 했는데

구글은 어째선지 여기로 안 들어가고 OidcUserService 로 들어가집니다...


![naverCustomUserService](https://user-images.githubusercontent.com/23338687/140527755-7c9f453f-000c-4b06-a0ee-c3a71da6c6f4.png)
<네이버, 등록한 CustomOAuthUserService 로 제대로 들어간다>

![OidcUserService](https://user-images.githubusercontent.com/23338687/140527765-8f17c6a3-7860-4331-aef9-745f9e39aafc.png)
<구글, CustomOAuthUserService 대신 OidcUserService 로 들어간다>

구글도 CustomOAuthUserService 로 들어가게 하려면 WebSecurityConfig 에서 추가로 설정해야 하는 부분이 있을까요?

**Comment by humanitas03** [comment]
@enjay27 
이건 가설인데요, 구글은 id가 아니라 sub를 키 명칭으로 가지고 있어서,
getAtrribute할 때 sub로 지정하면 혹시 들어오나요?

**Comment by enjay27** [comment]
> @humanitas03 구글과 네이버를 한 함수안에서 처리하고자 해서 그런건가요?

네 한 함수에서 처리하려고 했었는데... 안된다면 각각의 함수에서 처리하는 방법을 한번 찾아보겠습니다

**Comment by humanitas03** [comment]
@enjay27 
지금은 닫힌 PR 에서도 언급이 있었는데, 구글에서의 구현체가 네이버의 것과 달라서 생기는 이슈인것 같네요.(OidcUser)
https://github.com/2021-study/point-shop/pull/27#discussion_r740245304

**Comment by humanitas03** [comment]
@enjay27 

지금 단순하게 생각해봤는데 요렇게도 될까 싶네요???
![image](https://user-images.githubusercontent.com/16380977/140537561-c50f20e0-ce86-4b46-9679-4be15bf5fb8f.png)

**Comment by enjay27** [comment]
@humanitas03 
![GoogleOidcUserService](https://user-images.githubusercontent.com/23338687/140538951-b47b3b2f-2e55-4931-a31f-69ae2fec9365.png)

네 방금 확인했는데 따로 등록하면 구글도 잘 들어옵니다.

--- 

![cannotInherited](https://user-images.githubusercontent.com/23338687/140540434-903f5813-ff79-4949-929f-309da0aed384.png)

+각각 따로 구현을 해야겠네요.
