### ISSUE TITLE
API 구체화를 위한 문서화 작업에 대한 연구

### ISSUE THREAD

**Issue by humanitas03** [2021-study/point-shop#32]
## 설명(개인 Task 정도 입니다..)
>  내용 : 지금은 딱히 코딩을 진행 하는 것 보다는 설계를 가다듬는게 좋을듯 하여 이번주는 그림이나 좀 그려보는 시간을 가져보겠습니다.
> 저만 가지겠습니다... 그냥 뭘 같이 하자는 제안은 아니니... 무시해주세요...
> 프로젝트에 이상한 소스 만드는 그런 활동이 아닙니다;;

## 진행 사항
- [] 할일 1 : PlantUmL 도구로 핵심 API들에 대해서 시각화를 한번 시도(https://plantuml.com/ko/sequence-diagram)
- [] 할일 2 : IntelliJ 플러그인도 있고, 파일로 관리가 가능하지만 이부분은 조금 더 고민해보기
- [] 할일 3

**Comment by suhani93** [comment]
잠깐 봤는데 PlantUmL은 코드 기반으로 되는거 같은데 이 코드를 배워서 할만한 여유가 있을까요...?

**Comment by humanitas03** [comment]
아, 이거를 이슈로 남겨놔서 오해의 소지를 남겨놓았네요.
사실 지금 시점에서 저희가 설계 문서를 그닥 필요하다고 생각하지 않고, 새로운걸 같이 할 여유는 없을 것 같아요...

그냥 혼자 생각해보기에 .. Activity-Diagram, Sequence-Diagram 정도로 API 로직 처리 플로를 시각화 하면
모여서 이야기할 때 설계 의도를 표현하는게 어떨가 싶어서...

제가 혼자 생각하고 혼자 그려보려고 한거라서요...

나중에 마크다운 문서처럼 스크립트 베이스로 시각화 문서 만드는 툴은 한번 관심 있으신 분들만 보고 적용해보시면 좋을것 같아요..
-> 장점 : 개발자 입장에서는 코드로 관리되면 형상관리도 쉽고, 마우스로 끄는 것 보단 효율이 올라갑니다.



약간 마우스로 클릭클릭하면 짠하고 나오는 툴이 좋지 않을까요?
=> 그래픽 기반으로 오픈 소스로 가볍게 쓸만한건 **Star UML**이 있을 거 같네요

**Comment by humanitas03** [comment]
소스는 여기서 : https://github.com/humanitas03/point-shop/tree/activity-diagram-sample

* Oauth Client의 로그인 처리 Flow는 Sequence Diagram으로, 다른 부분들은 Activity Diagram으로 표현하였습니다.

### Oauth2
* 이건 저희가 구현하는 건 아니고, 설정만 잡으면 Spring Security가 다알아서 해주는 부분입니다.
![oauth2-sq](https://user-images.githubusercontent.com/16380977/140499518-3865732e-26a9-418e-bb94-1fb33c1e588b.png)
 

### 회원가입(메일 인증 이전)
![onboarding-ad](https://user-images.githubusercontent.com/16380977/140499600-dfa704c2-288b-4372-86fd-e18f4008e56f.png)

### 메일 검증
![onboarding-verifying-code](https://user-images.githubusercontent.com/16380977/140499759-b487ef59-c69b-42a0-96c2-eea9d20c13d7.png)

### 로그인 처리 상위 로직
![onboarding-after-verified-ad](https://user-images.githubusercontent.com/16380977/140499820-6f5a1d51-7a81-416d-9fe4-45a0dd159477.png)

* SNS와 자체 로그인 상세 구현부는 제작중
