### ISSUE TITLE
로컬에서 잘 돌아가는지 제대로 테스트 하지 못한 상황에서 올라간 PR에 대해서 강제로 한번 더 확인 할 수 있는 방법이 있나 찾아보자.

### ISSUE THREAD

**Issue by suhani93** [2021-study/point-shop#35]
## 설명
>  간단한 코드를 변경했다고 생각해서 로컬 TEST를 안 돌리고 커밋을 했더니... 그게 문제가 되어 TEST 코드가 정상적으로 실행되지 못함. 이러한 부분은 Github Action을 통해서 미리 방지할 수 있다고 어디서 봤던 거 같아서 해당 부분에 대해서 한번 찾아보자.

## 진행 사항
- [x] Github Action이 뭔지 찾아보기
- [ ] PR에 대해서 Test Code 로직을 돌리도록 Workflow 구성

**Comment by humanitas03** [comment]
Github action말고 Git action도 있나보네요?ㅎㅎ

**Comment by suhani93** [comment]
github action 입니다.. 밤에 잠깐 찾아본거라 잘 못 써놨네요.

**Comment by suhani93** [comment]
# Github Action 이란?

> Github Repository를 기반으로 소프트웨어 workflow를 자동화할 수 있도록 도와주는 도구이다. (CI/CD)



# Github Action 관련 개념

> Github Action을 이해하기 위해서 알아야 하는 개념은 **Workflow, Event, Job, Step, Action, Runner** 등이 있다.



1. Workflow
   - 최상위 개념으로 여러 Job으로 구성되고, Event에 의해 트리거될 수 있는 자동화된 프로세스
2. Event
   - Workflow를 실행하는 특정 활동이나 규칙 ( ex ) push, PR 등등)
3. Job 
   - Job은 여러 Step으로 구성되고, 가상 환경의 인스턴스에서 실행
4. Step
   - Job 안에서 순차적으로 실행되는 프로세스 단위
5. Action
   - job을 구성하기 위한 step들의 조합으로 구성된 독립적인 명령
6. Runner
   - Gitbub Action Runner 어플리케이션이 설치된 머신으로, Workflow가 실행될 인스턴스


그냥 CI/CD를 Github에서 하는 것이다.
